name: Build and Push Docker Image
on:
  push:
    branches:
      - main  # Change this to your main branch name

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        env:
          VERSION: v1.0.0  # Replace with your desired version
        run: |
          docker build -t warmestman/control:${{ env.VERSION }} .
          docker push warmestmane/control:${{ env.VERSION }}
