name: release
on:
  release:
    types: [created]
permissions:
  contents: write
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.2.0
      - uses: actions/checkout@v2
      - name: Fetch deps
        run: yarn
      - name: Build
        run: yarn webpack
      - name: Get release
        id: get_release
        uses: bruceadams/get-release@v1.2.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Package release
        run: cd dist && tar -zcvf numary-control.tar.gz . && mv numary-control.tar.gz ../
      - name: upload release
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.get_release.outputs.upload_url }}
          asset_path: release
          asset_name: numary-control-${{ steps.get_release.outputs.tag_name }}.tar.gz
          asset_content_type: application/gzip
      - name: upload release generic s3
        uses: zdurham/s3-upload-github-action@master
        with:
          args: --acl public-read
        env:
          FILE: numary-control.tar.gz
          AWS_REGION: 'eu-west-1'
          S3_BUCKET: 'numary-control-releases'
          S3_KEY: 'numary-control.tar.gz'
          AWS_ACCESS_KEY_ID: ${{ secrets.RELEASE_AWS_S3_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.RELEASE_AWS_S3_KEY_SECRET }}